context:
  name: py-rattler-build
  python_name: py_rattler_build
  version: "0.63.1"
  # fix is coming in rattler-build. Currently need to force usage so that it is recognized in `match`
  python_min: ${{ python_min }}

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ python_name[0] }}/${{ python_name }}/${{ python_name }}-${{ version }}.tar.gz
  sha256: df74b43a633a2bfa0d46816769039b945dc4043bb8442813a9f83783f730d060

build:
  number: 0
  skip: not (match(python, python_min ~ ".*") and is_abi3) or (target_platform == "linux-ppc64le")
  python:
    version_independent: true

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - maturin ~=1.2.1
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('rust') }}
    - cmake
    - if: unix
      then: make
    - cargo-bundle-licenses
  host:
    - python
    - python-abi3
    - maturin ~=1.2.1
    - pip
    - if: unix
      then: openssl
  run:
    - python

tests:
  - python:
      imports:
        - rattler_build
      pip_check: true

about:
  homepage: https://rattler.build/
  summary: 'The fastest way to build conda packages programatically'
  description: |
    The `rattler-build` tooling and library creates cross-platform relocatable
    binaries / packages from a simple recipe format. The recipe format is heavily
    inspired by `conda-build` and `boa`, and the output of a regular `rattler-build`
    run is a package that can be installed using `mamba`, `rattler` or `conda`.
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  documentation: https://rattler.build/latest/py-rattler-build/reference/
  repository: https://github.com/prefix-dev/rattler-build

extra:
  recipe-maintainers:
    - Hofer-Julian
    - wolfv
