context:
  name: py-rattler-build
  python_name: py_rattler_build
  version: "0.44.0"
  python_min: "3.9.*"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ python_name[0] }}/${{ python_name }}/${{ python_name }}-${{ version }}.tar.gz
  sha256: 8a536441b8068e9fca3a995811b0a7b457da28dc741c396f1e58d353d8c0904b

build:
  number: 0
  skip: not (match(python, python_min) and is_abi3 == 'true')
  python:
    version_independent: true

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - maturin ~=1.2.1
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - python-abi3
    - maturin ~=1.2.1
    - pip
    - if: unix
      then: openssl
  run:
    - python

tests:
  - python:
      imports:
        - rattler_build
      pip_check: true

about:
  homepage: http://rattler.build/
  summary: 'The fastest way to build conda packages programatically'
  description: |
    The `rattler-build` tooling and library creates cross-platform relocatable
    binaries / packages from a simple recipe format. The recipe format is heavily
    inspired by `conda-build` and `boa`, and the output of a regular `rattler-build`
    run is a package that can be installed using `mamba`, `rattler` or `conda`.
  license: BSD-3-Clause
  license_file: LICENSE
  documentation: https://rattler.build/latest/reference/python_bindings/
  repository: https://github.com/prefix-dev/rattler-build

extra:
  recipe-maintainers:
    - Hofer-Julian
    - wolfv
